linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

linters-settings:
  errcheck:
    disable: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
